[2025-10-25 22:05:11,796] ERROR — django.request: Internal Server Error: /ru/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\myproject\views.py", line 18, in home
    Listing.objects.filter(is_active=True, is_available=True)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1806, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'is_available' into field. Choices are: average_rating, reservations, created_at, deleted_at, description, id, image, is_active, is_deleted, location, owner, owner_id, price_eur, listing_type, rentals, feedbacks, rooms, status, title, updated_at, view_count, view_logs
[2025-10-27 16:55:33,717] ERROR â€” django.request: Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\myproject\views.py", line 28, in home
    return render(request, "index.html", {"listings": listings})
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property-detail-html' not found. 'property-detail-html' is not a valid view function or pattern name.
[2025-10-27 17:50:43,564] ERROR â€” django.request: Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\myproject\views.py", line 28, in home
    return render(request, "home.html", {"listings": listings})
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'listing-detail-html' not found. 'listing-detail-html' is not a valid view function or pattern name.
[2025-10-27 23:42:08,996] ERROR â€” django.request: Internal Server Error: /en/en/listings/2/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\views_html.py", line 97, in property_detail_html
    booking = Reservation.objects.create(
        user=request.user,
    ...<2 lines>...
        end_date=end_date_parsed,
    )
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\reservations\models\booking.py", line 78, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
    ~~~~~~~~~~~~~~^
        sender=origin,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        using=using,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\reservations\signals.py", line 24, in update_property_availability_on_booking
    property_obj.save(update_fields=["is_available"])
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\models\listing.py", line 105, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 880, in save
    raise ValueError(
    ...<3 lines>...
    )
ValueError: The following fields do not exist in this model, are m2m fields, primary keys, or are non-concrete fields: is_available
[2025-10-28 00:16:28,844] ERROR â€” django.request: Internal Server Error: /ru/en/listings/8/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\views_html.py", line 97, in property_detail_html
    booking = Reservation.objects.create(
        user=request.user,
    ...<2 lines>...
        end_date=end_date_parsed,
    )
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\reservations\models\booking.py", line 78, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
    ~~~~~~~~~~~~~~^
        sender=origin,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        using=using,
        ^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\reservations\signals.py", line 24, in update_property_availability_on_booking
    property_obj.status = Listing.AvailabilityStatus.RESERVED
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AvailabilityStatus' has no attribute 'RESERVED'
[2025-10-28 20:17:02,771] ERROR â€” django.request: Internal Server Error: /ru/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'language_switcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\myproject\views.py", line 28, in home
    return render(request, "home.html", {"listings": listings})
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'language_switcher' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
debugger_tags
highlighting
i18n
indent_text
l10n
log
rest_framework
static
syntax_color
tz
user_roles
widont
[2025-10-28 20:20:35,629] ERROR â€” django.request: Internal Server Error: /ru/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'language_switcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\myproject\views.py", line 28, in home
    return render(request, "home.html", {"listings": listings})
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'language_switcher' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
debugger_tags
highlighting
i18n
indent_text
l10n
log
rest_framework
static
syntax_color
tz
user_roles
widont
[2025-10-28 20:32:43,784] ERROR â€” django.request: Internal Server Error: /ru/listings/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\views_html.py", line 44, in property_list_html
    return render(request, "listings/property_list.html", {"listings": listings})
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property-detail-html' not found. 'property-detail-html' is not a valid view function or pattern name.
[2025-10-29 08:01:02,554] ERROR â€” django.request: Internal Server Error: /api/v1/feedbacks/
[2025-10-29 08:57:32,956] ERROR â€” django.request: Internal Server Error: /api/v1/register/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: users_userprofile.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\users\views.py", line 77, in post
    user = serializer.save()
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\users\serializers.py", line 39, in create
    UserProfile.objects.create(user=user, user_type=tenant_type)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: users_userprofile.user_id
[2025-10-29 11:40:07,155] ERROR â€” django.request: Internal Server Error: /api/v1/listings/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\views.py", line 64, in list
    response = super().list(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\pagination.py", line 222, in paginate_queryset
    return list(self.page)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\paginator.py", line 191, in __len__
    return len(self.object_list)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 131, in __iter__
    setattr(obj, attr_name, row[col_pos])
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'popularity_score' of 'Listing' object has no setter
[2025-10-29 11:41:11,889] ERROR â€” django.request: Internal Server Error: /api/v1/listings/1/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\views.py", line 97, in retrieve
    instance = self.get_object()
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\generics.py", line 100, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 131, in __iter__
    setattr(obj, attr_name, row[col_pos])
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'popularity_score' of 'Listing' object has no setter
[2025-10-29 12:16:55,768] ERROR â€” django.request: Internal Server Error: /api/v1/listings/1/
Traceback (most recent call last):
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\apps\listings\views.py", line 97, in retrieve
    instance = self.get_object()
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\generics.py", line 100, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ICH\PycharmProjects\Rental_HUB\backend\.venv\Lib\site-packages\django\db\models\query.py", line 131, in __iter__
    setattr(obj, attr_name, row[col_pos])
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'popularity_score' of 'Listing' object has no setter
